# 예외
- 프로그램을 설계할 때 실행시 예외 상황을 예측하여 사전에 예외 처리가 되도록 한다
- 이때 적절한 조치가 없으면 프로그램은 에러가 나며 멈춰버린다
- 예상 외의 상황에 적절한 조치를 취하는 방법을 배운다

## 에러의 종류
1. 문법 에러 (syntax error) - 사람의 실수
    - 언어의 문법 규칙을 따르지 않아 발생하는 에러
    - 주로 컴파일 또는 인터프리터 단계에서 발견된다
    - ex) 괄호 닫지 않음, 잘못된 키워드 사용
2. 실행 시 에러 (runtime error)  
    - 프로그램이 실행되는 도중에 발생하는 에러
    - 주로 예상하지 못한 상황이나 외부 요인 때문에 발생한다  
    - ex) 파일 찾을 수 없음, 네트워크 통신 불가, 메모리 부족
3. 논리 에러 (logic error) - 사람의 실수
    - 문법적으로는 맞지만, 의도한 대로 작동하지 않아 발생하는 에러
    - 주로 잘못된 알고리즘이나 논리 구조 때문에 발생한다  
    - ex) 잘못된 수식 or 조건문을 사용하여 원하는 결과를 얻지 못하는 경우

## 에러 상황별 처리

| | 문법 에러 (syntax error)| 실행 시 에러 (runtime error)| 논리 에러 (logic error)|
|-|-|-|-|
| **원인**| 코드의 형식적 오류| 실행 중에 예상외의 사태가 발생하여 동작이 중지됨 | 기술한 처리 내용에 논리적인 오류가 있음|
| **아는 방법**  | 컴파일하면 에러 남| 실행하면 도중에 강제 종료 됨| 실행하면 예상외의 값이 나옴|
| **해결 방법**  | 컴파일러의 지적을 보고 수정 | 에러 원인을 찾아서 수정 | 원인을 스스로 찾아서 해결해야 함|

## 예외를 처리하는 여러가지 방식
### throw Exception
- throw 키워드를 사용해서 예외를 발생시킨다
```dart
void checkValue(int value) {
  if (value < 0) {
    throw Exception('Value cannot be negative');
  }
}
```
### try, catch, finally
- try: 예외가 발생할 수 있는 코드를 포함
- catch: 예외가 발생했을 때 실행할 코드
- finally: 예외 발생 여부와 상관없이 항상 실행할 코드
- e: 에러의 정보를 담고 있는 객체

```dart
void main() {
  try {
    checkValue(-1);
  } catch (e) {
    print('Caught an exception: $e');
  } finally {
    print('This code runs no matter what');
  }
}
```

### on
- 특정 예외 타입을 잡고 싶을 때 on 키워드를 사용할 수 있다
```dart
void main() {
  try {
    checkValue(-1);
  } on FormatException catch (e) {
    print('Caught a FormatException: $e');
  } catch (e) {
    print('Caught an exception: $e');
  } finally {
    print('This code runs no matter what');
  }
}
```

### 사용자 정의 예외
- 필요에 따라 사용자 정의 예외 클래스를 만들 수 있다
```dart
class NegativeValueException implements Exception {
  final String? _message;

  NegativeValueException([this._message]);

  @override
  String toString() {
    if (_message == null) return 'NegativeValueException';
    return 'NegativeValueException: $_message';
  }
}

void checkValue(int value) {
  if (value < 0) {
    throw NegativeValueException('Value cannot be negative');
  }
}

void main() {
  try {
    checkValue(-1);
  } catch (e) {
    print('Caught an exception: $e');
  }
}
```

### rethrow
- 예외를 다시 던질 때 사용하는 키워드 (에러 처리를 미룬다)
- 예외를 처리하는 도중에 동일한 예외를 다시 던져서 상위 호출 스택에서 처리하게 해준다
- 예외를 잡고, 로그를 남기거나 일부 처리를 한 후에 동일한 예외를 다시 던지는 상황에서 사용
```dart
void main(List<String> arguments) {
  try {
    someError2();
  } catch (e) {
    print(e);
  }
}

void someError2() {
  try {
    someError();
  } catch (e) {
    rethrow;
  }
}

void someError() {
  // 뭔가를 하는 코드
  throw FormatException('에러가 발생했습니다.');
}
```

